Vagrant.configure("2") do |config|
  # Use a compatible Ubuntu box for macOS Intel with VirtualBox
  config.vm.box = "bento/ubuntu-20.04" # "ubuntu/focal64"

  # Server Node
  config.vm.define "amentagS" do |server|
    server.vm.hostname = "amentagS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-server" # <<< Add this line to give it a unique VM name
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
    chmod +x /vagrant/scripts/install_k3s_server.sh
    /vagrant/scripts/install_k3s_server.sh
    SHELL
  end
end
