Vagrant.configure("2") do |config|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"

  # Server Node
  config.vm.define "amentagS" do |server|
    server.vm.hostname = "amentagS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "vmware_desktop" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant/scripts/install_k3s_server.sh
      /vagrant/scripts/install_k3s_server.sh
    SHELL
  end

  # Worker Node
  config.vm.define "mtigunitSW" do |worker|
    worker.vm.hostname = "mtigunitSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "vmware_desktop" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant/scripts/install_k3s_agent.sh
      /vagrant/scripts/install_k3s_agent.sh
    SHELL
  end
end
